In [2]:
!python3 -V

Python 3.12.3


In [4]:
!python3 -m venv ./env

In [9]:
!source ../env/bin/activate

/bin/sh: 1: source: not found


## Practice

In [1]:
import torch
import torchvision
import torchaudio

In [5]:
torch.__version__

'2.5.1+cu124'

In [4]:
scalar = torch.tensor(7)
scalar.item()

7

In [6]:
scalar.shape

torch.Size([])

In [7]:
scalar.ndim

0

In [13]:
s = torch.tensor([2])
s.item()

2

In [14]:
rand = torch.rand((3, 4))
rand

tensor([[0.4063, 0.6300, 0.3166, 0.2628],
        [0.2206, 0.5456, 0.9109, 0.5065],
        [0.6960, 0.9453, 0.2638, 0.5156]])

In [17]:
print(torch.cuda.device_count())
print(torch.cuda.is_available())
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

1
True


'cuda'

In [18]:
tensor = torch.tensor([[1, 2],
                       [3, 4]])
print(tensor, tensor.device)

tensor = tensor.to(device)
print(tensor, tensor.device)

tensor([[1, 2],
        [3, 4]]) cpu
tensor([[1, 2],
        [3, 4]], device='cuda:0') cuda:0


In [19]:
tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [20]:
tensor.cpu().numpy()

array([[1, 2],
       [3, 4]])

## Questions

### Question - 1

In [109]:
import torch
import numpy 

In [66]:
a = torch.tensor([[[1,2],
                   [3,4]],
                  [[5,6],
                   [7,8]]])
print(a, a.shape)

a = a.reshape((1, 8))
print(a, a.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) torch.Size([2, 2, 2])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]]) torch.Size([1, 8])


In [63]:
a = torch.tensor([[[1,2],
                   [3,4]],
                  [[5,6],
                   [7,8]]])
print(a.shape)
print(a.view((2, 4)).shape)

torch.Size([2, 2, 2])
torch.Size([2, 4])


In [82]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())

x = x.squeeze()
print(x.size())

x = x.unsqueeze(dim=1)
x.size()

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])


torch.Size([2, 1, 2, 2])

In [39]:
a = torch.tensor([[1,2],
                  [3,4]])
b = torch.tensor([[5,6],
                  [7,8]])
print('a: ', a, '\nb: ', b, '\n')

print(torch.stack([a, b], dim=0), '\n')

print(torch.stack([a, b], dim=1), '\n')

print(torch.stack([a, b], dim=2), '\n')

a:  tensor([[1, 2],
        [3, 4]]) 
b:  tensor([[5, 6],
        [7, 8]]) 

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) 

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]]) 

tensor([[[1, 5],
         [2, 6]],

        [[3, 7],
         [4, 8]]]) 



In [111]:
a = torch.tensor([[1,2],
                  [3,4]])
b = torch.tensor([[5,6],
                  [7,8]])
print('a: ', a, '\nb: ', b, '\n')

print(torch.cat([a, b], dim=0), '\n')

print(torch.cat([a, b], dim=1), '\n')

print("Below error is because cat only uses existing dimensions, whereas stack creates a new dimension.")
print(torch.cat([a, b], dim=2), '\n')

a:  tensor([[1, 2],
        [3, 4]]) 
b:  tensor([[5, 6],
        [7, 8]]) 

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) 

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]]) 

Below error is because cat only uses existing dimensions, whereas stack creates a new dimension.


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

### Question - 2

In [56]:
a = torch.tensor([[[1,2],
                   [3,4]],
                  [[5,6],
                   [7,8]]])
print(a)
a.permute(dims=(1, 0, 2))

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])

In [58]:
x = torch.randn(2, 3, 5)
print(x.size())
print(torch.permute(x, (2, 0, 1)).size())

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


### Question - 3

In [88]:
a = torch.tensor([[[1,2],
                   [3,4]],
                  [[5,6],
                   [7,8]]])
a[1, 1, 0]

tensor(7)

### Question - 4

In [23]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

tensor = torch.tensor(arr)
print(tensor)

arr = tensor.numpy()
print(arr)

[1 2 3]
tensor([1, 2, 3])
[1 2 3]


### Question - 5

In [95]:
rand = torch.rand((7,7))
rand, rand.size()

(tensor([[0.7574, 0.1196, 0.9840, 0.7984, 0.5040, 0.7022, 0.3512],
         [0.4204, 0.5641, 0.5446, 0.2947, 0.6954, 0.9367, 0.3253],
         [0.9952, 0.6627, 0.4953, 0.8281, 0.5989, 0.6021, 0.9675],
         [0.6458, 0.6529, 0.9242, 0.3216, 0.5808, 0.8255, 0.7844],
         [0.4870, 0.9821, 0.4089, 0.6696, 0.3977, 0.3235, 0.1164],
         [0.8459, 0.4397, 0.0656, 0.7068, 0.6545, 0.8021, 0.7125],
         [0.3435, 0.0650, 0.1429, 0.0552, 0.8913, 0.6286, 0.3326]]),
 torch.Size([7, 7]))

### Question - 6

In [96]:
rand2 = torch.rand((1, 7))
result = rand @ rand2.view((7, 1))
result, result.size()

(tensor([[1.3748],
         [1.4235],
         [1.8917],
         [1.7718],
         [1.1055],
         [1.6721],
         [0.8888]]),
 torch.Size([7, 1]))

### Question - 7

In [97]:
a = torch.rand((2, 3))
b = torch.rand((2, 3))

a = a.to(device)
b = b.to(device)

print(a, a.device)
print(b, b.device)

tensor([[0.5104, 0.0122, 0.9317],
        [0.1460, 0.9159, 0.0127]], device='cuda:0') cuda:0
tensor([[0.7312, 0.4531, 0.0250],
        [0.3671, 0.0736, 0.3916]], device='cuda:0') cuda:0


### Question - 8

In [98]:
c = a @ b.view((3, 2))
print(c, c.size())

tensor([[0.4421, 0.6005],
        [0.1306, 0.4074]], device='cuda:0') torch.Size([2, 2])


### Question - 9

In [113]:
print(c)

print(c.min(), c.max())

tensor([[0.4421, 0.6005],
        [0.1306, 0.4074]], device='cuda:0')
tensor(0.1306, device='cuda:0') tensor(0.6005, device='cuda:0')


### Question - 10

In [106]:
print(c)

c.argmin(), c.argmax()

tensor([[0.4421, 0.6005],
        [0.1306, 0.4074]], device='cuda:0')


(tensor(2, device='cuda:0'), tensor(1, device='cuda:0'))

### Question - 11

In [116]:
rand = torch.rand(size=(1,1,1,10))
print(rand, rand.shape)

rand1 = rand.reshape(-1,)
print(rand1, rand1.shape)

tensor([[[[0.3391, 0.9511, 0.4698, 0.2057, 0.2057, 0.5141, 0.3187, 0.9428,
           0.3312, 0.4732]]]]) torch.Size([1, 1, 1, 10])
tensor([0.3391, 0.9511, 0.4698, 0.2057, 0.2057, 0.5141, 0.3187, 0.9428, 0.3312,
        0.4732]) torch.Size([10])


In [118]:
rand2 = rand.squeeze()
print(rand2)
rand2.shape

tensor([0.3391, 0.9511, 0.4698, 0.2057, 0.2057, 0.5141, 0.3187, 0.9428, 0.3312,
        0.4732])


torch.Size([10])